### ISSUE TITLE
Articles Count

### ISSUE THREAD

**Issue by akhil-naidu** [TeaGuns/odin#2]
The number of articles within a category and subcategory is not dynamic. Even though a number of new articles/posts are assigning to the category, the number of articles variable is not updating on the website.

**Comment by nickmccullum** [comment]
I encountered the same bug. I think the easiest fix is to simply replace the article count with a static description of that category.

**Comment by TomBillingtonUK** [comment]
You can set the size manually by adding a size attribute in the category_list.yml file for each category. For example:
```
#This file defines all the categories you are using
account:
  name: My Account
  description: How to make changes and update your account
  size: 1
payments:
  name: Payments
  description: How to get your payment and more
  size: 17
```

in index.html I then swapped the category size code to 

```
{% if category[1].size == 1 %}
    <p class="m-0">{{ category[1].size }} article</p>
 {% else %}
    <p class="m-0">{{ category[1].size }} articles</p>
{% endif %}`
```
